name: Update Anywhere ReFilter rules

on:
  workflow_dispatch:

  schedule:
    - cron: "17 3 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Build Anywhere rule sets
        run: python build_anywhere_refilter.py

      - name: Commit updated rules
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add dist/*.arrs

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "chore: update Anywhere ReFilter rules"
          git push
